locale                   : "en-US"
title                    : "Diyorbek Pulatov"
title_separator          : "-"
name                     : &name "Diyorbek Pulatov"
description              : &description "Astronomer | CMEs, Space Weather & Solar Wind Researcher"
url                      : "https://YOUR_GITHUB_USERNAME.github.io"
baseurl                  : "/pulatov.github.io"
repository               : "YOUR_GITHUB_USERNAME/pulatov.github.io"

author:
  name             : "Diyorbek Pulatov"
  avatar           : "diyorbek.jpg"
  bio              : "Astronomer | Space Weather Researcher"
  location         : "Samarkand, Uzbekistan"
  employer         : "Samarkand State University"
  email            : "diyorbekpolatov2002@gmail.com"
  googlescholar    : ""
  orcid            : ""
  researchgate     : ""
  scopus           : ""
  github           : ""
  linkedin         : ""
